### ISSUE TITLE
Just curious if PPO was chosen for a reason

### ISSUE THREAD

**Issue by slerman12** [facebookresearch/level-replay#3]
Is there a reason why the base alg chosen was PPO? Just wondering. Seems like a more recent algorithm, or something like Rainbow, might be equally suitable. (Is procgen discrete or continuous?)

**Comment by minqi** [comment]
Hi, thanks for your interest in this repo. To answer your questions:
- We chose PPO because that is the standard baseline used in the original Procgen study as well as most follow-up works. It thus serves as the natural baseline for evaluating the effect of autocurricula inducde by PLR.
- Procgen has a discrete action space.
